### ISSUE TITLE
Offerwall & Survey together

### ISSUE THREAD

**Issue by PhilE88** [pollfish/react-native-plugin-pollfish#8]
We want to initialize one button to do Offerwall and one to do survey. It seems like the RNPollfish is a singleton, so I'm not sure how to implement an Offerwall button and a Survey button side by side. Can you provide an example of how this could work?

**Comment by fotism23** [comment]
Hey @PhilE88 

Just a heads up, we've got a game-changing update coming to the React Native Plugin most likely late January. The new version will allow you to load multiple ad units or placements simultaneously—no more choosing between Offerwall and Survey, you can have both at once!

Keep your eyes peeled on the repository for the latest updates.
